name: Auto Add to Project

on:
  issues:
    types:
      - opened

jobs:
  auto-add-to-project:
    runs-on: ubuntu-latest

    steps:
    - name: Add to Project
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: add-to-project-${{ github.event.issue.number }}
        commit-message: "Auto add to project"
        title: "Add to Project"
        body: "Automatically added to project board with status TODO."
